### ISSUE TITLE
buff_server

### ISSUE THREAD

**Issue by ChrisLinn** [PRIEWIENV/BytomLit#5]
利用 
https://github.com/oysheng/bufferserver

它帮我们检索了utxo， 还有可以方便地导入钱包、发合约。

有需要的话，修改返回数据。包括  raw_tx，  或者 utxo 信息

中心化一点的话, 仲裁也可以通过它来做了。可以先简单实现 不带 revoke 的

**Comment by 0xmountaintop** [comment]
go mod 不太好弄，我不太熟。  我先直接 git clone https://github.com/oysheng/bufferserver $GOPATH/src/github.com/bufferserver

调试完再  覆盖回来

**Comment by 0xmountaintop** [comment]
还是不行，能获取到的数据不够用
